name: Build and Test
on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Firebase Emulator Suite
        run: npm install -g firebase-tools@9.19.0

      - name: Install Dependencies
        run: npm install
    
      - name: Setup service account
        run: | 
          mkdir .local
          echo '{"type":"service_account","project_id":"english-challenge-test","private_key":"${{secrets.FIREBASE_TEST_SA_PRIVATE_KEY}}","client_email":"${{secrets.FIREBASE_TEST_SA_CLIENT_EMAIL}}","client_x509_cert_url":"${{secrets.FIREBASE_TEST_SA_CLIENT_CERT_URL}}"}' >> .local/maracuja-challenge-dev.json
          
      - name: Run all the tests
        uses: w9jds/firebase-action@master
        with: 
          args: emulators:exec --project english-challenge-test \"npm run test-before-deploy\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions 
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # GCP_SA_KEY: ${{ secrets.DEV_FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: english-challenge-test


  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: Checkout Repo
  #     #   uses: actions/checkout@master
  #     # - name: Install Dependencies
  #     #   run: npm install
  #     # - name: Archive Production Artifact
  #     #   uses: actions/upload-artifact@master
  #     #   with:
  #     #     name: dist
  #     #     path: .
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      # - name: Download Artifact
      #   uses: actions/download-artifact@master
      #   with:
      #     name: dist
      #     path: .
      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # GCP_SA_KEY: ${{ secrets.DEV_FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: english-challenge-test


