module.exports = {
  HOME: "/",
  LANDING: "/landing",
  SIGN_UP: "/signup",
  SIGN_UP_CLUBPICKER: "/signup-clubpicker",
  SIGN_UP_REFERRAL: "/signup-referral",
  SIGN_UP_LEAGUEPICKER: "/signup-leaguepicker",
  LEAGUE_WELCOME: "/signup-league/:leagueId",
  SIGN_UP__CLUB: "/signup-clubs/:clubId",
  SIGN_UP__PHONE: "/signup-phone",
  SIGN_UP__EMAILLINK: "/signup-emaillink",
  SIGN_UP__FACEBOOK: "/signup-facebook",
  SIGN_UP__EMAILPASSWORD_VALIDATION: "/signup-emailvalidation",
  SIGN_UP__EMAIL_VERIFIED: "/email-verified",
  SIGN_UP__EMAILPASSWORD_CONFIRM: "/email-confirmed",
  SIGN_UP__EMAILPASSWORD_CONFIRM_LANDING: "/signup-email-confirmed-landing",
  SIGN_UP__WHITE_LIST: "/signup-white-list",
  SIGN_UP__LICENSE: "/signup-license",
  SIGN_UP__EMAILPASSWORD: "/signup-emailpassword",
  SIGN_UP__PASSWORD_FORGET: "/signup-password-forget",
  SIGN_UP__PHONE_CONFIRM: "/signup-phone-confirm",
  SIGN_UP__RESTRICTED: "/signup-restricted",
  SIGN_UP__INFO: "/signup-info",
  SIGN_UP__CONFIRM: "/signup-confirm",
  SIGN_UP__ONBOARDING_PLAYERCARD: "/signup-card",
  SIGN_IN: "/signin",
  CGU: "/cgu",
  PRIVACY: "/privacy",
  SETTINGS: "/settings",

  // PLAYER
  EDIT_CURRENT_PLAYER: "/player/edit",
  VIEW_PLAYER_CARD: "/player/card",
  PLAYER_CALENDAR: "/players/:playerId/calendar",

  // CHALLENGE
  JOIN_CHALLENGE: "/join/:challengeCode",
  CHALLENGE_WITH_ID: "/joinchallenge/:challengeId",
  CHALLENGE: "/challenge/home",
  ACTIVE_RANKING: "/challenge/ranking/",
  RANKING: "/challenge/ranking/:rankingId",
  CALENDAR: "/challenge/calendar",
  CALENDAR_QUIZZES: "/challenge/calendar/quizzes",
  ACTIVE_CLUB: "/challenge/club/",
  EDIT_ACTIVE_CLUB: "/challenge/club/edit",
  CLUB: "/challenge/club/:teamId",
  ONBOARDING_WELCOME: "/welcome",
  ONBOARDING_NEED_CAPTAIN: "/need-captain",
  CHALLENGE_RULES: "/rules",
  LOTTERIES: "/lotteries",
  LOTTERY: "/lotteries/:lotteryId",
  SURVEY: "/surveys/:surveyId",
  // ICEBREAKER_CREATE: '/icebreaker/:icebreakerId',
  EXTERNAL_ACTIVITY: "/externalActivities/:externalActivityId",
  IDEAS_BOXES: "/ideas-boxes",
  IDEAS_BOX: "/ideas-boxes/:ideasBoxId",
  EVENTS: "/events",
  EVENT: "/events/:eventId",
  EVENT_SUBSCRIPTION_SAVED: "/events/:eventId/subscription-saved",

  // CONTESTS
  CONTEST: "/contests/:questionSetId",
  CONTEST_PLAY: "/contests/:questionSetId/play",
  CONTEST_INTRO: "/contests/:questionSetId/intro",
  CONTEST_CONGRATS: "/contests/:questionSetId/congrats",

  // CONTESTS
  ICEBREAKER: "/icebreakers/:questionSetId",
  ICEBREAKER_CREATE_QUESTION: "/icebreaker/create-question",
  ICEBREAKER_CREATE_QUESTION_SUCCESS: "/icebreaker/create-question/success",
  ICEBREAKER_PLAY: "/icebreakers/:questionSetId/play",
  ICEBREAKER_INTRO: "/icebreakers/:questionSetId/intro",
  ICEBREAKER_CONGRATS: "/icebreakers/:questionSetId/congrats",

  // CONTESTS
  DEBRIEFING: "/debriefings/:questionSetId",
  DEBRIEFING_PLAY: "/debriefings/:questionSetId/play",
  DEBRIEFING_INTRO: "/debriefings/:questionSetId/intro",
  DEBRIEFING_CONGRATS: "/debriefings/:questionSetId/congrats",

  // TRAININGS
  TRAINING: "/trainings/:questionSetId",
  TRAINING_PLAY: "/trainings/:questionSetId/play",
  TRAINING_INTRO: "/trainings/:questionSetId/intro",
  TRAINING_CONGRATS: "/trainings/:questionSetId/congrats",

  GAMES: "/games/:questionSetId",
  GAMES_PLAY: "/games/:questionSetId/play",
  GAMES_INTRO: "/games/:questionSetId/intro",
  GAMES_CONGRATS: "/games/:questionSetId/congrats",
  GAMES_FUN_FACT: "/games/:questionSetId/fun-fact",
}

// export const CLUBS = '/clubs/:clubId'
